### ISSUE TITLE
ISSUE with Twitter Login

### ISSUE THREAD

**Issue by inickiran** [scrisoft/midrub_cms#11]
Hello, 

we have followed the documentation and created a twitter app with v1 api, (stand alone App). Stil its not working.

After authentication its redirected to auth/42 page but showing total blank page.

Thanks,

**Comment by scrisoft** [comment]
Twitter app should be created with two version 1 and 2. Should be exactly like is configured the administrator -> user -> networks -> twitter. Otherwise won't work. Should be correct all redirects: 3

**Comment by inickiran** [comment]
I have doubled check the settings and followed all instructions and enabled the network.

Still we are redirected to a blank page with auth/42 URL.

Please guide us, also there is no db entry is happening for this user.

**Comment by inickiran** [comment]
1) we are not able to login using twitter
2) we are not able to connect the account form scheduler for twitter.

**Comment by scrisoft** [comment]
Please follow the documentation. https://cms.midrub.com/articles/how-to-configure-twitter-for-login-and-sign-up

Twitter is easy to be configured.

Please don't abuse. Use only to report, not to ask for support.

**Comment by inickiran** [comment]
Hello,

We are not abusing, we are not doing this first time.
Twitter app is setup correctly as per the guideline and still it's showing blank page after it's coming back to call back url, which shows the blank page, and DB entery is not happening for new user.

So it' s bug.

Thanks,

**Comment by scrisoft** [comment]
In my demo it works. I know there isn't a bug because someone in the last summer has reported a lot same problem until i've seen it didn't followed my video where i'm showing how is configured my app. 

If you wish to use Twitter login, follow even one thousands of times the video until you will make it work, otherwise don't use the Twitter login.

**Comment by inickiran** [comment]
Hello,

We were not abusing, it's a fault of scope you have written in the code and documentation. May be you need to update your documentation for twitter scope OR default scope you have written with in your code.

AS per the latest API update form twitter to get the user profile data from twitter API, you need to pass two scope in combination "**user.read and tweet.read**". then only it will work.
specifically for elevated apps created under having both API support.

Here is your code snippet.
--------
BY DEFAULT you have passed below two scope "offline.access and users.read"
        // Scopes to request
        $scopes = array(
            'offline.access',
            'users.read'
        );

AND you are taking additional scope from the settings if exist. as per your documentation you have only mentioned "tweet.write"

        // Verify if additional scopes exists
        if ( md_the_option('network_twitter_scopes') )

-----------------

AS soon as we have added tweet.read in settings it has worked.

**Comment by inickiran** [comment]
Here is the link where i have found the solution.

https://github.com/florianmartens/passport-twitter-oauth2.0/issues/1

[alphatownsman](https://github.com/alphatownsman) commented [on Apr 1](https://github.com/florianmartens/passport-twitter-oauth2.0/issues/1#issuecomment-1085416357)
@nbrady-techempower I encountered similar issue but not using any code in this repo.

It seems to be an issue in Twitter's implementation on API scopes. Basically, in order to access https://api.twitter.com/2/users/me, you have to pass at least users.read tweet.read in scope, users.read alone won't work.

**Comment by scrisoft** [comment]
No, for login/signup is used this application\base\admin\components\collection\frontend\networks\collection\twitter.php

Anything is correct in application\base\user\networks\collection\twitter.php

I won't add there new scopes because you have additional scopes field to add the wanted scopes. 

And I have written about 4 required scopes to add in the field additional scopes https://www.midrub.com/articles/how-to-configure-the-twitter-api-for-the-crm-social-app

**Comment by scrisoft** [comment]
tweet.read is for reading of the tweets. It has nothing with our login/sign up. It is required in the user -> networks list because is used for posting. But for login is just required the user's id and email. Other things aren't necessary.

**Comment by inickiran** [comment]
We are refering to crm social app and plugin documentation, from code
canyon. Which comes with bunch. In that in tweet.write is mentioned anyway
thanks.
