### ISSUE TITLE
Showing Error in Member area settings page

### ISSUE THREAD

**Issue by inickiran** [scrisoft/midrub_cms#12]
Hello, 

WE have updated again php8.1 as suggested by you. to get support for youtube.

Again PHP warning error is showing under members' login settings page. 
https://smm.cohort.work/user/app/crm_settings

Here is the screenshot.
<img width="1993" alt="Screenshot 2022-11-23 at 10 27 31 AM" src="https://user-images.githubusercontent.com/118817300/203472088-649d2c8b-2b20-40d1-ae01-d827611d5bb3.png">

**Comment by inickiran** [comment]
Is there any resolution on this error?

**Comment by scrisoft** [comment]
Show me which time zone you have selected. 

I'm using too php 8,1 but can't reproduce the error.

**Comment by scrisoft** [comment]
No, I know where is. 

In  My profile you have selected a time zone. I have tried to get same error, but wasn't able.

**Comment by inickiran** [comment]
I am in india timezone, so i have selected, asia/colombo which is nearest to us, as we are not able to find Asia/kolkatta.
+5:30
Thanks

**Comment by inickiran** [comment]
Hey, Great, as soon as i have updated to asia/colombo, the error has gone.

Thanks,

**Comment by scrisoft** [comment]
I will change the time zone list in  this week and the error should be removed.

**Comment by scrisoft** [comment]
Get all updates. I have modified the time zones list.

**Comment by inickiran** [comment]
Thanks,
*Kiran Jadav*
Delivery Head
IndiaNIC Infotech Limited

www.IndiaNIC.com <http://www.indianic.com/>
*Skype: *kiran_jadav  | Whats app : +91 97243 10545

*Mobile:* +91-97243 10545 ( India )

Profile: *goo.gl/2O6vs4 <http://goo.gl/2O6vs4>*
