### ISSUE TITLE
Cron Job for Hostinger is the same as the example above (doesnt work)

### ISSUE THREAD

**Issue by 7figurefortune** [scrisoft/midrub_cms#14]
wget -O –spider https://www.midrub.com/cron-job >/dev/null 2>&1

You have to add your url instead https://www.midrub.com/

These commands aren't supported by all server. For example Hostinger requires a file instead url. Or other server could request a different cron command format. 

For Hostinger you can use this command:

wget -O –spider https://www.midrub.com/cron.php >/dev/null 2>&1

**Comment by scrisoft** [comment]
It can't work. This command is not for Hostinger. 

I just showed an example with the file instead the cron-job url.

On Hostinger you have to add the path to the file cron.php https://support.hostinger.com/en/articles/1583465-how-to-set-up-a-cron-job-at-hostinger
