### ISSUE TITLE
404 not found

### ISSUE THREAD

**Issue by ukenmaulana** [scrisoft/midrub_cms#17]
Hi there, i have installed midrub cms and follow the instruction on youtube video.
But after installation, it should show login page.
It's not appear on me. It always show 404 not found on url : https://websitename/auth/signin

Could you help me how to fix this ?

**Comment by scrisoft** [comment]
Hi, configure the plans from the administrator panel.

**Comment by ukenmaulana** [comment]
How can i login into administrator panel when my software did not work ?
I just bought crm social from code canyon and it need midrub cms first.
