### ISSUE TITLE
An uncaught Exception was encountered

### ISSUE THREAD

**Issue by ukenmaulana** [scrisoft/midrub_cms#18]
Hi there,, i've installed midrub cms and then CRM Social.
Then i install wordpress pro, copy that php file into my server as the documentation show.

But suddenly it appear like this. 

An uncaught Exception was encountered

Type: Error

Message: Call to undefined function CmsBase\User\Apps\Collection\Crm_social\the_crm_apps_installed_app()

Filename: /home/sukabu12/multipost.my.id/application/base/user/apps/collection/crm_social/main.php

Line Number: 63

How can i fix this ?

**Comment by scrisoft** [comment]
Hi,

You have to install even this https://github.com/scrisoft/crm

You could read about in the CRM Social documentation.
