### ISSUE TITLE
error

### ISSUE THREAD

**Issue by obaviet** [scrisoft/midrub_cms#5]
I just installed it successfully and am planning to buy some of your plugins but I think I have a few errors.
1, I don't have user theme
![Chụp web_10-2-2022_134912_swispy net](https://user-images.githubusercontent.com/4661721/153355755-a1a217a7-8ffa-4cef-b26c-27ebf546b518.jpeg)
2, it looks like my admin theme is not like your demos
3, I got logged out after a few minutes of admin login
4, Why don't you sell all plugins in 1 package. For us it can help save money

**Comment by obaviet** [comment]
5, i cant change admin pass https://nimb.ws/Xpdhbu

**Comment by scrisoft** [comment]
Hi,

In config.php change TRUE to FALSE for sess_match_ip

For other questions follow exactly the installation guide here https://www.midrub.com/articles/how-to-install-and-configure-the-crm-moderator-app-1
