### ISSUE TITLE
view networks for users

### ISSUE THREAD

**Issue by smartselwadydev** [scrisoft/midrub_cms#9]
how to view (posts - Facebook Pages) in users panel ?

**Comment by scrisoft** [comment]
Should be installed an app which has support for posts.

**Comment by smartselwadydev** [comment]
how can i get Repost App 
i buy the source from
 https://codecanyon.net/item/midrub-schedule-and-publish-on-the-most-popular-social-networks/17447773

but now i removed 
how can i get the full script ?

**Comment by scrisoft** [comment]
You need to use this version https://github.com/scrisoft/midrub_cms_0_0_8_4

Contact me by email.
